# Generated by Django 6.0.6 on 2026-06-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_founditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='status',
            field=models.CharField(default='Found', max_length=20),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='status',
            field=models.CharField(default='Lost', max_length=20),
        ),
    ]
