# Generated by Django 6.0.6 on 2026-06-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_founditem_status_lostitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='found_items/'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
    ]
