# Generated by Django 6.0.6 on 2026-06-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='is_recovered',
            field=models.BooleanField(default=False),
        ),
    ]
