# Generated by Django 6.0.6 on 2026-06-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_lostitem_is_recovered'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='claim_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
